spring:
  data:
   cassandra:
     schema-action: CREATE_IF_NOT_EXISTS
     contact-points: localhost
     keyspace-name: message_key_space
topic1:
  boot: message
topic2:
  boot: channel
groupId1:
  boot: message_group_persist
groupId2:
  boot: channel_group_persist     
