spring:
    data:
        mongodb:
            database: SearchServiceDB
            host: localhost
            password: root123
            port: 27017
            username: root
search-topic:
    boot: search_user
groupId:
    boot: search_user_group
server:
    boot: 172.23.239.122:9092
