spring:
    data:
        mongodb:
            database: UserServiceDb
            host: localhost
            password: root12
            port: 27017
            username: root12
topic:
    boot: user_details 
search-topic:
    boot: search_user
groupId:
  boot: user_group
server:
  boot: 172.23.239.122:9092
