spring:
    data:
        mongodb:
            database: UserServiceDb
            host: localhost
            password: root12
            port: 27017
            username: root12
topic:
    boot: user_details 
